/*
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class DddWebModule extends AbstractDddWebModule {
}
