/*
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDddScopeProvider extends DelegatingScopeProvider {
}
