/*
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DddRuntimeModule extends AbstractDddRuntimeModule {
}
