/*
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DddStandaloneSetup extends DddStandaloneSetupGenerated {

	def static void doSetup() {
		new DddStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
