/**
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl;

import org.domaindriven.model.dsl.AbstractDddRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DddRuntimeModule extends AbstractDddRuntimeModule {
}
