/**
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl;

import org.domaindriven.model.dsl.DddStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DddStandaloneSetup extends DddStandaloneSetupGenerated {
  public static void doSetup() {
    new DddStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
