/**
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl.scoping;

import org.domaindriven.model.dsl.scoping.AbstractDddScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DddScopeProvider extends AbstractDddScopeProvider {
}
