/**
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl.ide;

import org.domaindriven.model.dsl.ide.AbstractDddIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DddIdeModule extends AbstractDddIdeModule {
}
