/**
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.domaindriven.model.dsl.DddRuntimeModule;
import org.domaindriven.model.dsl.DddStandaloneSetup;
import org.domaindriven.model.dsl.ide.DddIdeModule;
import org.domaindriven.model.dsl.web.DddWebModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class DddWebSetup extends DddStandaloneSetup {
  @Override
  public Injector createInjector() {
    DddRuntimeModule _dddRuntimeModule = new DddRuntimeModule();
    DddIdeModule _dddIdeModule = new DddIdeModule();
    DddWebModule _dddWebModule = new DddWebModule();
    return Guice.createInjector(Modules2.mixin(_dddRuntimeModule, _dddIdeModule, _dddWebModule));
  }
}
