/**
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl.web;

import org.domaindriven.model.dsl.web.AbstractDddWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class DddWebModule extends AbstractDddWebModule {
}
