/*
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl.parser.antlr;

import com.google.inject.Inject;
import org.domaindriven.model.dsl.parser.antlr.internal.InternalDddParser;
import org.domaindriven.model.dsl.services.DddGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DddParser extends AbstractAntlrParser {

	@Inject
	private DddGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDddParser createParser(XtextTokenStream stream) {
		return new InternalDddParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Application";
	}

	public DddGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DddGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
