/**
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl.validation;

import org.domaindriven.model.dsl.validation.AbstractDddValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DddValidator extends AbstractDddValidator {
}
