/*
 * generated by Xtext 2.17.0.M2
 */
package org.domaindriven.model.dsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DddWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDddWebModule extends DefaultWebModule {

}
